package com.wd.health.core.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wd.health.model.bean.UserInfoBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO_BEAN".
*/
public class UserInfoBeanDao extends AbstractDao<UserInfoBean, Long> {

    public static final String TABLENAME = "USER_INFO_BEAN";

    /**
     * Properties of entity UserInfoBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Age = new Property(0, int.class, "age", false, "AGE");
        public final static Property Email = new Property(1, String.class, "email", false, "EMAIL");
        public final static Property HeadPic = new Property(2, String.class, "headPic", false, "HEAD_PIC");
        public final static Property Height = new Property(3, int.class, "height", false, "HEIGHT");
        public final static Property Id = new Property(4, Long.class, "id", true, "_id");
        public final static Property InvitationCode = new Property(5, String.class, "invitationCode", false, "INVITATION_CODE");
        public final static Property JiGuangPwd = new Property(6, String.class, "jiGuangPwd", false, "JI_GUANG_PWD");
        public final static Property NickName = new Property(7, String.class, "nickName", false, "NICK_NAME");
        public final static Property SessionId = new Property(8, String.class, "sessionId", false, "SESSION_ID");
        public final static Property Sex = new Property(9, int.class, "sex", false, "SEX");
        public final static Property UserName = new Property(10, String.class, "userName", false, "USER_NAME");
        public final static Property Weight = new Property(11, int.class, "weight", false, "WEIGHT");
        public final static Property WhetherBingWeChat = new Property(12, int.class, "whetherBingWeChat", false, "WHETHER_BING_WE_CHAT");
        public final static Property Status = new Property(13, int.class, "status", false, "STATUS");
    }


    public UserInfoBeanDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO_BEAN\" (" + //
                "\"AGE\" INTEGER NOT NULL ," + // 0: age
                "\"EMAIL\" TEXT," + // 1: email
                "\"HEAD_PIC\" TEXT," + // 2: headPic
                "\"HEIGHT\" INTEGER NOT NULL ," + // 3: height
                "\"_id\" INTEGER PRIMARY KEY ," + // 4: id
                "\"INVITATION_CODE\" TEXT," + // 5: invitationCode
                "\"JI_GUANG_PWD\" TEXT," + // 6: jiGuangPwd
                "\"NICK_NAME\" TEXT," + // 7: nickName
                "\"SESSION_ID\" TEXT," + // 8: sessionId
                "\"SEX\" INTEGER NOT NULL ," + // 9: sex
                "\"USER_NAME\" TEXT," + // 10: userName
                "\"WEIGHT\" INTEGER NOT NULL ," + // 11: weight
                "\"WHETHER_BING_WE_CHAT\" INTEGER NOT NULL ," + // 12: whetherBingWeChat
                "\"STATUS\" INTEGER NOT NULL );"); // 13: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserInfoBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getAge());
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(2, email);
        }
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(3, headPic);
        }
        stmt.bindLong(4, entity.getHeight());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(5, id);
        }
 
        String invitationCode = entity.getInvitationCode();
        if (invitationCode != null) {
            stmt.bindString(6, invitationCode);
        }
 
        String jiGuangPwd = entity.getJiGuangPwd();
        if (jiGuangPwd != null) {
            stmt.bindString(7, jiGuangPwd);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(8, nickName);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(9, sessionId);
        }
        stmt.bindLong(10, entity.getSex());
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(11, userName);
        }
        stmt.bindLong(12, entity.getWeight());
        stmt.bindLong(13, entity.getWhetherBingWeChat());
        stmt.bindLong(14, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserInfoBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getAge());
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(2, email);
        }
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(3, headPic);
        }
        stmt.bindLong(4, entity.getHeight());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(5, id);
        }
 
        String invitationCode = entity.getInvitationCode();
        if (invitationCode != null) {
            stmt.bindString(6, invitationCode);
        }
 
        String jiGuangPwd = entity.getJiGuangPwd();
        if (jiGuangPwd != null) {
            stmt.bindString(7, jiGuangPwd);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(8, nickName);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(9, sessionId);
        }
        stmt.bindLong(10, entity.getSex());
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(11, userName);
        }
        stmt.bindLong(12, entity.getWeight());
        stmt.bindLong(13, entity.getWhetherBingWeChat());
        stmt.bindLong(14, entity.getStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4);
    }    

    @Override
    public UserInfoBean readEntity(Cursor cursor, int offset) {
        UserInfoBean entity = new UserInfoBean( //
            cursor.getInt(offset + 0), // age
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // email
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // headPic
            cursor.getInt(offset + 3), // height
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // id
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // invitationCode
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // jiGuangPwd
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // nickName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // sessionId
            cursor.getInt(offset + 9), // sex
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // userName
            cursor.getInt(offset + 11), // weight
            cursor.getInt(offset + 12), // whetherBingWeChat
            cursor.getInt(offset + 13) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserInfoBean entity, int offset) {
        entity.setAge(cursor.getInt(offset + 0));
        entity.setEmail(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHeadPic(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHeight(cursor.getInt(offset + 3));
        entity.setId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setInvitationCode(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setJiGuangPwd(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setNickName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSessionId(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSex(cursor.getInt(offset + 9));
        entity.setUserName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setWeight(cursor.getInt(offset + 11));
        entity.setWhetherBingWeChat(cursor.getInt(offset + 12));
        entity.setStatus(cursor.getInt(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserInfoBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserInfoBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserInfoBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
